### ISSUE TITLE
Media buttons not working (OSX 10.10.3)

### ISSUE THREAD

**Issue by marnickmenting** [marcw/twentytwo#1]
Great app! The media buttons don't seem to work. Is there anything I need to change? Can I help debugging? I tried the Soundcleod app and the media buttons do work with that one. I use an iMac 2008 with OSX 10.10.3, TwentyTwo version 0.2.0.

**Comment by marcw** [comment]
Hello, this software isn't actively maintained... You can still submit a PR that I will gladly merge. Otherwise, you can have a look at http://beardedspice.com/

**Comment by marnickmenting** [comment]
Thanks. BeardedSpice provides the functionality I need concerning media keys, but I miss the separate window feature. I used Fluid to create a separate window and dock launch icon, but BeardedSpice does not work with that. Any ideas?

**Comment by marcw** [comment]
nope, sorry :-/
