### ISSUE TITLE
Can't login to My22 Account

### ISSUE THREAD

**Issue by garretthyder** [marcw/twentytwo#2]
Hello,

Love the app, found sadly I couldn't get the Social Signon to work for any of the services (Google+, Twitter, Facebook). You'll find these when you go to the My22 tab as it prompts login.

Clicking opens in my web browser, which I can authorize or sign-in but that's not reflected within the app.

I'm on OS X Yosemite (10.10.5) using TwentyTwo (0.2.0)

Thanks

**Comment by marcw** [comment]
Hey,

Sorry, TwentyTwo isn't supported anymore... You can maybe use https://github.com/beardedspice/beardedspice instead.

**Comment by garretthyder** [comment]
Thanks @marcw good to know I'll check it out. Cheers
